name: baegopa
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  go_router: ^14.6.1
  icons_launcher: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  custom_lint: ^0.7.0
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

flutter:

  uses-material-design: true

  assets:
    - lib/core/img/

icons_launcher:
  image_path: "lib/core/img/app_launch_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true